### ISSUE TITLE
potential mismatch in system definition

### ISSUE THREAD

**Issue by crazy-matt** [kclejeune/system#219]
Hi Kennan,

I'm not sure if the below is intentional but if it is then I'm a bit confused as your only home-manager config calling the hm/work.nix is a x86_64-linux.

https://github.com/kclejeune/system/blob/969ac3d513e28d02cb2ce42d00605732fd4bf37c/flake.nix

**Comment by kclejeune** [comment]
> Hi Kennan,
> 
> 
> 
> I'm not sure if the below is intentional but if it is then I'm a bit confused as your only home-manager config calling the hm/work.nix is a x86_64-linux.
> 
> 
> 
> https://github.com/kclejeune/system/blob/969ac3d513e28d02cb2ce42d00605732fd4bf37c/flake.nix
> 
> 

I'm not sure if I follow - I only use that config on servers at work, so it only needs the x86_64-linux definition. I don't run CI checks on that config, so there's no need for any others.

I have other configs defined for my personal system so that I can test them in CI, but I don't necessarily use them all.

**Comment by crazy-matt** [comment]
ok got you. Thanks for the explanation.
